Repository Swift-Coding-Club/throw_away, pull requests merged in 2022-11, with the labels that each got.

#11 Feat add object view 8
  ThrowAway/ThrowAway.xcodeproj/project.pbxproj
  ThrowAway/ThrowAway/AddObject/AddObjectView.swift
  ThrowAway/ThrowAway/AddObject/PhotoPicker.swift
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/calendar.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/calendar.imageset/calendar.png
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/objectImagePlaceholder.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/objectImagePlaceholder.imageset/objectImagePlaceholder.png
Labels: 📱 design, ✨ feature

#16 [Design] 통계뷰(StatisticsView) #7
  ThrowAway/ThrowAway.xcodeproj/project.pbxproj
  ThrowAway/ThrowAway/AddObject/AddObjectView.swift
  ThrowAway/ThrowAway/AddObject/PhotoPicker.swift
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/calendar.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/calendar.imageset/calendar.png
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/objectImagePlaceholder.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Addobject/objectImagePlaceholder.imageset/objectImagePlaceholder.png
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test01.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test01.imageset/Test01.jpeg
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test02.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test02.imageset/Test02.jpeg
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test03.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test03.imageset/Test03.jpeg
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test04.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/TestImage/Test04.imageset/Test04.jpeg
  ThrowAway/ThrowAway/StatisticsView/CalendarManager.swift
  ThrowAway/ThrowAway/StatisticsView/DateHolder.swift
  ThrowAway/ThrowAway/StatisticsView/Month.swift
  ThrowAway/ThrowAway/StatisticsView/View/CalendarView.swift
  ThrowAway/ThrowAway/StatisticsView/View/DateScrollView.swift
  ThrowAway/ThrowAway/StatisticsView/View/DayOfWeekView.swift
  ThrowAway/ThrowAway/StatisticsView/View/StatisticsView.swift
  ThrowAway/ThrowAway/ThrowAwayApp.swift
Labels: 📱 design

#13 coredata CUD 테스트코드 작성
  ThrowAway/Product+CoreDataClass.swift
  ThrowAway/Product+CoreDataProperties.swift
  ThrowAway/ThrowAway.xcodeproj/project.pbxproj
  ThrowAway/ThrowAway/Assets.xcassets/lipstic.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/lipstic.imageset/[에르메스] 루즈 에르메스 새틴 립스틱.png
  ThrowAway/ThrowAway/ContentView.swift
  ThrowAway/ThrowAway/Persistence.swift
  ThrowAway/ThrowAway/ThrowAway.xcdatamodeld/ThrowAway.xcdatamodel/contents
  ThrowAway/ThrowAwayTests/ThrowAwayTests.swift
Labels: ✅ test

#26 Feat setting view 20
  ThrowAway/ThrowAway.xcodeproj/project.pbxproj
  ThrowAway/ThrowAway/Assets.xcassets/Setting/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Setting/buymeacoffee.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Setting/buymeacoffee.imageset/buymeacoffee.png
  ThrowAway/ThrowAway/Assets.xcassets/Setting/github.imageset/Contents.json
  ThrowAway/ThrowAway/Assets.xcassets/Setting/github.imageset/logo-github.png
  ThrowAway/ThrowAway/SwiftUI/SettingView/SettingView.swift
  ThrowAway/ThrowAway/SwiftUI/SettingView/SettingViewCell.swift
  ThrowAway/ThrowAway/SwiftUI/SettingView/SettingViewModel.swift
  ThrowAway/ThrowAway/View Controllers/TabBarViewController.swift
Labels: 🚚 resource, 📱 design

#25 [Feature] 리스트 화면 비움, 삭제 처리
  ThrowAway/ThrowAway.xcodeproj/project.pbxproj
  ThrowAway/ThrowAway/View Controllers/ProductListViewController.swift
  ThrowAway/ThrowAway/Views/ProductTableViewCell.swift
Labels: ✨ feature

#30 [Feature] 통계뷰(StatisticsView) 지정된 날짜만 배경색 입히기
  ThrowAway/ThrowAway/SwiftUI/StaticsView/CalendarManager.swift
  ThrowAway/ThrowAway/SwiftUI/StaticsView/Model/Month.swift
  ThrowAway/ThrowAway/SwiftUI/StaticsView/View/CalendarView.swift
  ThrowAway/ThrowAway/SwiftUI/StaticsView/View/StatisticsView.swift
Labels: ✨ feature
